on:
    workflow_dispatch:
        inputs:
            name:
                description: "Name"
                required: true
                default: "Tanmay"
            city:
                description: "City"
                required: true
                default: "Ahmedabad"
            country:
                description: "Country"
                required: true
                default: "India"

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
                run: echo "Hello ${{ github.event.inputs.name }}!"
            - name: List Files
                run: ls -la
            - name: Checkout
                uses: actions/checkout@v4
            - name: List Files
                run: ls -la
    print-info:
        runs-on: ubuntu-latest
        steps:
            - name: Print Input information
              run: |
                echo "Name: ${{ github.event.inputs.name }}"
                echo "City: ${{ github.event.inputs.city }}"
                echo "Country: ${{ github.event.inputs.country }}"
            - name: Get Temperature of City
              run: |
                curl -X GET "https://api.openweathermap.org/data/2.5/weather?q=${{ github.event.inputs.city }}&appid=b5596ea48c699f703ca54f52350bc2d2&units=metric"
